//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.PlayerGame = new HashSet<PlayerGame>();
            this.Room = new HashSet<Room>();
            this.Message = new HashSet<Message>();
            this.GameEvent = new HashSet<GameEvent>();
        }
    
        public int GameId { get; set; }
        public System.Guid Token { get; set; }
        public Nullable<System.Guid> EndToken { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<LibrairieService.Models.GameEndReason> EndReason { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool IsTakingDisconnectDecision { get; set; }
    
        public virtual ICollection<PlayerGame> PlayerGame { get; set; }
        public virtual ICollection<Room> Room { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<GameEvent> GameEvent { get; set; }
    }
}
