//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    
    public enum GameEventType : short
    {
        PLAYER_CHANGE = 1,
        DRAW_CARD = 2,
        PLAY_CARD = 3
    }
}
