//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class GameEvent
    {
        public int GameEventId { get; set; }
        public bool ServerEvent { get; set; }
        public System.DateTime Date { get; set; }
        public GameEventType Type { get; set; }
        public int GameId { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
