//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Game = new HashSet<Game>();
            this.Room = new HashSet<Room>();
        }
    
        public int MessageId { get; set; }
        public System.DateTime Date { get; set; }
        public MessageType Type { get; set; }
        public string Content { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Game> Game { get; set; }
        public virtual ICollection<Room> Room { get; set; }
    }
}
