//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilleBornesEntities : DbContext
    {
        public MilleBornesEntities()
            : base("name=MilleBornesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Game> Game { get; set; }
        public DbSet<GameEvent> GameEvent { get; set; }
        public DbSet<LoggedInUser> LoggedInUser { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<PlayerGame> PlayerGame { get; set; }
        public DbSet<PlayerRoomState> PlayerRoomState { get; set; }
        public DbSet<Room> Room { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<PrivateMessage> PrivateMessage { get; set; }
    }
}
