//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.PlayerRoomState = new HashSet<PlayerRoomState>();
            this.Message = new HashSet<Message>();
        }
    
        public int RoomId { get; set; }
        public string Name { get; set; }
        public int MasterUserId { get; set; }
        public bool Started { get; set; }
        public Nullable<int> GameInProgressId { get; set; }
        public System.Guid Token { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<PlayerRoomState> PlayerRoomState { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Message> Message { get; set; }
    }
}
