//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrairieService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Message = new HashSet<Message>();
            this.PlayerGame = new HashSet<PlayerGame>();
            this.PlayerRoomState = new HashSet<PlayerRoomState>();
            this.Room = new HashSet<Room>();
            this.PlayerChangeEvent = new HashSet<PlayerChangeEvent>();
            this.DrawCardEvent = new HashSet<DrawCardEvent>();
            this.PrivateMessage = new HashSet<PrivateMessage>();
            this.PrivateMessage1 = new HashSet<PrivateMessage>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual LoggedInUser LoggedInUser { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<PlayerGame> PlayerGame { get; set; }
        public virtual ICollection<PlayerRoomState> PlayerRoomState { get; set; }
        public virtual ICollection<Room> Room { get; set; }
        public virtual ICollection<PlayerChangeEvent> PlayerChangeEvent { get; set; }
        public virtual ICollection<DrawCardEvent> DrawCardEvent { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessage { get; set; }
        public virtual ICollection<PrivateMessage> PrivateMessage1 { get; set; }
    }
}
