//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lobby.LobbyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomInfo", Namespace="http://schemas.datacontract.org/2004/07/LibrairieService.Models")]
    [System.SerializableAttribute()]
    public partial class RoomInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterName {
            get {
                return this.MasterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterNameField, value) != true)) {
                    this.MasterNameField = value;
                    this.RaisePropertyChanged("MasterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMessage", Namespace="http://schemas.datacontract.org/2004/07/LibrairieService.Models")]
    [System.SerializableAttribute()]
    public partial class UserMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyService.ILobbyService")]
    public interface ILobbyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/CreateRoom", ReplyAction="http://tempuri.org/ILobbyService/CreateRoomResponse")]
        System.Nullable<System.Guid> CreateRoom(string name, System.Guid roomMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinRoom", ReplyAction="http://tempuri.org/ILobbyService/JoinRoomResponse")]
        bool JoinRoom(System.Guid player, System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinRoomGameEnd", ReplyAction="http://tempuri.org/ILobbyService/JoinRoomGameEndResponse")]
        bool JoinRoomGameEnd(System.Guid player, System.Guid gameEndToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/LeaveRoom", ReplyAction="http://tempuri.org/ILobbyService/LeaveRoomResponse")]
        bool LeaveRoom(System.Guid player, System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetReady", ReplyAction="http://tempuri.org/ILobbyService/SetReadyResponse")]
        bool SetReady(System.Guid player, bool ready);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SendRoomMessage", ReplyAction="http://tempuri.org/ILobbyService/SendRoomMessageResponse")]
        bool SendRoomMessage(System.Guid player, System.Guid room, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetConfig", ReplyAction="http://tempuri.org/ILobbyService/SetConfigResponse")]
        bool SetConfig(System.Guid player, System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetName", ReplyAction="http://tempuri.org/ILobbyService/SetNameResponse")]
        bool SetName(System.Guid player, System.Guid room, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetMaster", ReplyAction="http://tempuri.org/ILobbyService/SetMasterResponse")]
        bool SetMaster(System.Guid player, System.Guid room, string newMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetOpenRoomsInfo", ReplyAction="http://tempuri.org/ILobbyService/GetOpenRoomsInfoResponse")]
        System.Collections.Generic.List<Lobby.LobbyService.RoomInfo> GetOpenRoomsInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetLoggedUsers", ReplyAction="http://tempuri.org/ILobbyService/GetLoggedUsersResponse")]
        System.Collections.Generic.Dictionary<string, byte> GetLoggedUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetRoomPlayers", ReplyAction="http://tempuri.org/ILobbyService/GetRoomPlayersResponse")]
        System.Collections.Generic.List<string> GetRoomPlayers(System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetRoomMessages", ReplyAction="http://tempuri.org/ILobbyService/GetRoomMessagesResponse")]
        System.Collections.Generic.List<Lobby.LobbyService.UserMessage> GetRoomMessages(System.Guid room, int limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetMasterName", ReplyAction="http://tempuri.org/ILobbyService/GetMasterNameResponse")]
        string GetMasterName(System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetTeam", ReplyAction="http://tempuri.org/ILobbyService/SetTeamResponse")]
        bool SetTeam(System.Guid player, System.Guid room, int team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetCurrentTeamIndex", ReplyAction="http://tempuri.org/ILobbyService/GetCurrentTeamIndexResponse")]
        int GetCurrentTeamIndex(System.Guid player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SetRoomName", ReplyAction="http://tempuri.org/ILobbyService/SetRoomNameResponse")]
        bool SetRoomName(System.Guid room, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetCurrentGameToken", ReplyAction="http://tempuri.org/ILobbyService/GetCurrentGameTokenResponse")]
        System.Nullable<System.Guid> GetCurrentGameToken(System.Guid room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetNewMessageFrom", ReplyAction="http://tempuri.org/ILobbyService/GetNewMessageFromResponse")]
        System.Collections.Generic.List<Lobby.LobbyService.UserMessage> GetNewMessageFrom(System.Guid player, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/DoTheBigBastardThatWaveHisFlagHasNewMessageFromS" +
            "omeoneIfSoTellMeLad", ReplyAction="http://tempuri.org/ILobbyService/DoTheBigBastardThatWaveHisFlagHasNewMessageFromS" +
            "omeoneIfSoTellMeLadResponse")]
        System.Collections.Generic.List<string> DoTheBigBastardThatWaveHisFlagHasNewMessageFromSomeoneIfSoTellMeLad(System.Guid player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/SendPrivateMessage", ReplyAction="http://tempuri.org/ILobbyService/SendPrivateMessageResponse")]
        bool SendPrivateMessage(System.Guid from, string to, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyServiceChannel : Lobby.LobbyService.ILobbyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyServiceClient : System.ServiceModel.ClientBase<Lobby.LobbyService.ILobbyService>, Lobby.LobbyService.ILobbyService {
        
        public LobbyServiceClient() {
        }
        
        public LobbyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LobbyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<System.Guid> CreateRoom(string name, System.Guid roomMaster) {
            return base.Channel.CreateRoom(name, roomMaster);
        }
        
        public bool JoinRoom(System.Guid player, System.Guid room) {
            return base.Channel.JoinRoom(player, room);
        }
        
        public bool JoinRoomGameEnd(System.Guid player, System.Guid gameEndToken) {
            return base.Channel.JoinRoomGameEnd(player, gameEndToken);
        }
        
        public bool LeaveRoom(System.Guid player, System.Guid room) {
            return base.Channel.LeaveRoom(player, room);
        }
        
        public bool SetReady(System.Guid player, bool ready) {
            return base.Channel.SetReady(player, ready);
        }
        
        public bool SendRoomMessage(System.Guid player, System.Guid room, string message) {
            return base.Channel.SendRoomMessage(player, room, message);
        }
        
        public bool SetConfig(System.Guid player, System.Guid room) {
            return base.Channel.SetConfig(player, room);
        }
        
        public bool SetName(System.Guid player, System.Guid room, string newName) {
            return base.Channel.SetName(player, room, newName);
        }
        
        public bool SetMaster(System.Guid player, System.Guid room, string newMaster) {
            return base.Channel.SetMaster(player, room, newMaster);
        }
        
        public System.Collections.Generic.List<Lobby.LobbyService.RoomInfo> GetOpenRoomsInfo() {
            return base.Channel.GetOpenRoomsInfo();
        }
        
        public System.Collections.Generic.Dictionary<string, byte> GetLoggedUsers() {
            return base.Channel.GetLoggedUsers();
        }
        
        public System.Collections.Generic.List<string> GetRoomPlayers(System.Guid room) {
            return base.Channel.GetRoomPlayers(room);
        }
        
        public System.Collections.Generic.List<Lobby.LobbyService.UserMessage> GetRoomMessages(System.Guid room, int limit) {
            return base.Channel.GetRoomMessages(room, limit);
        }
        
        public string GetMasterName(System.Guid room) {
            return base.Channel.GetMasterName(room);
        }
        
        public bool SetTeam(System.Guid player, System.Guid room, int team) {
            return base.Channel.SetTeam(player, room, team);
        }
        
        public int GetCurrentTeamIndex(System.Guid player) {
            return base.Channel.GetCurrentTeamIndex(player);
        }
        
        public bool SetRoomName(System.Guid room, string newName) {
            return base.Channel.SetRoomName(room, newName);
        }
        
        public System.Nullable<System.Guid> GetCurrentGameToken(System.Guid room) {
            return base.Channel.GetCurrentGameToken(room);
        }
        
        public System.Collections.Generic.List<Lobby.LobbyService.UserMessage> GetNewMessageFrom(System.Guid player, string name) {
            return base.Channel.GetNewMessageFrom(player, name);
        }
        
        public System.Collections.Generic.List<string> DoTheBigBastardThatWaveHisFlagHasNewMessageFromSomeoneIfSoTellMeLad(System.Guid player) {
            return base.Channel.DoTheBigBastardThatWaveHisFlagHasNewMessageFromSomeoneIfSoTellMeLad(player);
        }
        
        public bool SendPrivateMessage(System.Guid from, string to, string message) {
            return base.Channel.SendPrivateMessage(from, to, message);
        }
    }
}
